<a href="https://colab.research.google.com/github/Linda-Nwabunike/Data-science-batch-A/blob/main/linda_assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Addition of arrays


In [ ]:
import numpy as np
arr_x=([[20,40,60],[30,45,75]])
arr_y=([[10,15,25],[50,65,85]])
#addition of array with the plus sign
arr_x= np.array([[20,40,60],[30,45,75]])
arr_y= np.array([[10,15,25],[50,65,85]])

print("Array X")
print (arr_x,'\n')

print("Array Y")
print(arr_y,'\n')

print("Direct Addition")
print(arr_x + arr_y,'\n')


Array X
[[20 40 60]
 [30 45 75]] 

Array Y
[[10 15 25]
 [50 65 85]] 

Direct Addition
[[ 30  55  85]
 [ 80 110 160]] 



Subtraction of Arrays


In [ ]:
#subtraction
print("Direct Subtraction")
print(arr_x- arr_y)

Direct Subtraction
[[ 10  25  35]
 [-20 -20 -10]]


Multiplication of Arrays

In [ ]:
#MULTIPLICATION
a=5
print(np.multiply(arr_x,a))

[[100 200 300]
 [150 225 375]]


Division of Arrays


In [ ]:
#Division
b=10
print(np.divide(arr_y,b))


[[1.  1.5 2.5]
 [5.  6.5 8.5]]


In [ ]:
import pandas as pd
#Creating from a list of lists
pet_info = [['Howard', 10, 'Goat'], ['Lucy', 4 , 'Fish'], ['Roco', 8, 'Lizard']]
pet_info

[['Howard', 10, 'Goat'], ['Lucy', 4, 'Fish'], ['Roco', 8, 'Lizard']]

In [ ]:
pet_df = pd.DataFrame(pet_info, columns = ['Name', 'Age', 'Type'],
                      index = ['A', 'B', 'C'])
                     
pet_df

Name  Age    Type
A  Howard   10    Goat
B    Lucy    4    Fish
C    Roco    8  Lizard

In [ ]:
pet_df['Name']

A    Howard
B      Lucy
C      Roco
Name: Name, dtype: object

In [ ]:
pet_df[['Name','Age']]

Name  Age
A  Howard   10
B    Lucy    4
C    Roco    8

In [ ]:
pet_df['Type']

A      Goat
B      Fish
C    Lizard
Name: Type, dtype: object

In [ ]:
type(pet_df)

pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

Download weight-height csv database

In [ ]:
import pandas as pd
from google.colab import files
uploaded =files.upload()

Saving weight-height.csv to weight-height.csv


Reading of csv.dataset using pandas


In [ ]:
#reading of csv.dataset using pandas
import io
df=pd.read_csv(io.BytesIO(uploaded['weight-height.csv']))
df

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

Displaying the fifth Datapoint

In [21]:
df.loc[5]

Gender       Male
Height     67.253
Weight    152.212
Name: 5, dtype: object

In [26]:
df['Height']

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...    
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64